#!/bin/sh

IFS=
while read line; do
	if [ "${line:0:1}" == / ]; then
		echo;
		while read source; do
			if expr match "$source" "\s*[a-z0-9]*:" > /dev/null; then break; fi;
			printf ";%s\n" "$source";
		done;
		echo;
		line="$source";
	fi;
	echo "$line";
done